name: Publish PyPI Package


on:
  push:
    tags:
      - "*"

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'

      - name: Build Distribution Archive
        run: |
          python -m pip install --upgrade build hatchling
          python -m build

      - name: Store Distribution Packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  # NOTE: Publishing is a different job to reduce the amount of things that can potentially abuse the `id-token: write` permission
  publish-artifacts:
    runs-on: ubuntu-latest
    needs: build-artifacts
    environment:
      name: pypi
      url: https://pypi.org/p/leapfrogai
    permissions:
      id-token: write

    steps:
      - name: Download Distribution Packages
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      # publish package to PyPI via Trusted Publish Managment (uses OIDC for auth)
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true