name: Publish PyPI Package


on:
  push:
    tags:
      - "*"

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version-file: 'pyproject.toml'

      - name: Build Distribution Archive
        run: |
          python -m pip install --upgrade build hatchling
          python -m build

      - name: Store Distribution Packages
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: python-package-distributions
          path: dist/

  # NOTE: Publishing is a different job to reduce the amount of things that can potentially abuse the `id-token: write` permission
  publish-artifacts:
    runs-on: ubuntu-latest
    needs: build-artifacts
    environment:
      name: pypi
      url: https://pypi.org/p/leapfrogai
    permissions:
      id-token: write

    steps:
      - name: Download Distribution Packages
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: python-package-distributions
          path: dist/

      # publish package to PyPI via Trusted Publish Managment (uses OIDC for auth)
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
        with:
          verbose: true
          print-hash: true
