name: Run Tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  "build-310":
    name: Build and Test on Python 3.10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: '>=3.10 <3.11'

    - name: install deps
      run: make requirements-dev

    - name: install module in editable mode
      run: pip install -e .

    - name: Tests
      run: make test
  build:
    name: "Build on latest"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version-file: 'pyproject.toml'

    - name: install deps
      run: make requirements-dev

    - name: install module in editable mode
      run: pip install -e .

    - name: Tests
      run: make test
